root: true

env:
  browser: false
  node: true

plugins:
  - "node"

extends:
  - "airbnb"
  - "eslint:recommended"
  - "plugin:node/recommended"

rules:
  vars-on-top: 0
  no-plusplus: 0
  no-console: 0
  no-restricted-syntax: 0
  arrow-body-style: 0
  comma-dangle:
    - 0
    - functions: 2