dist: trusty
language: node_js
node_js:
  - '7'
branches:
  only:
    - master
    - dev
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash'
  - 'export PATH=$HOME/.yarn/bin:$PATH'
  - npm install -g dredd@3.4.5
install:
  - yarn install
script:
  - yarn lint
  - yarn test
before_script:
  - dredd
