dist: trusty

language: node_js
node_js:
  - "7"

branches:
  only:
    - master
    - dev

cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

before_install:
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn lint
  - yarn test
